prometheus:
  url: "http://prometheus-service:9090"

pushgateway:
  url: "pushgateway:9091"

monitoring:
  interval: 60000

spring:
  application:
    name: ai-sidecar
  main:
    web-application-type: none

logging:
  level:
    root: INFO
    com.example.ai_sidecar: DEBUG